# coding: utf-8

"""
    Investabit

    The Investabit API allows for access to all of the public facing services provided, including market data and forecasts.  ## General Overview  1. All API methods will be built to adhere to RESTful best practices as closely as possible. As such, all API calls will be made via the standard HTTP protocol using the GET/POST/PUT/DELETE request types.  2. Every request returns the status as a JSON response with the following   - success, true if it was successful   - code, the http status code (also in the response header)          200 if response is successful          400 if bad request          401 if authorization JWT is wrong or limit exceeded          404 wrong route          500 for any internal errors  - status, the status of the request, default **success**  - errors, an array of any relevant error details  3. For any requests that are not successful an error message is specified and returned as an array for the **errors** key in the JSON response.  4. All authentication uses JSON Web Tokens (JWT), which is set as the **Authorization** entry in the header, see the following for more details.     * http://jwt.io     * https://scotch.io/tutorials/the-anatomy-of-a-json-web-token  # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PublicPriceChangeResponseDataPriceChange(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'interval': 'str',
        'change_usd': 'float',
        'change_pct': 'float'
    }

    attribute_map = {
        'interval': 'interval',
        'change_usd': 'change_usd',
        'change_pct': 'change_pct'
    }

    def __init__(self, interval=None, change_usd=None, change_pct=None):  # noqa: E501
        """PublicPriceChangeResponseDataPriceChange - a model defined in Swagger"""  # noqa: E501

        self._interval = None
        self._change_usd = None
        self._change_pct = None
        self.discriminator = None

        self.interval = interval
        self.change_usd = change_usd
        self.change_pct = change_pct

    @property
    def interval(self):
        """Gets the interval of this PublicPriceChangeResponseDataPriceChange.  # noqa: E501


        :return: The interval of this PublicPriceChangeResponseDataPriceChange.  # noqa: E501
        :rtype: str
        """
        return self._interval

    @interval.setter
    def interval(self, interval):
        """Sets the interval of this PublicPriceChangeResponseDataPriceChange.


        :param interval: The interval of this PublicPriceChangeResponseDataPriceChange.  # noqa: E501
        :type: str
        """
        if interval is None:
            raise ValueError("Invalid value for `interval`, must not be `None`")  # noqa: E501

        self._interval = interval

    @property
    def change_usd(self):
        """Gets the change_usd of this PublicPriceChangeResponseDataPriceChange.  # noqa: E501


        :return: The change_usd of this PublicPriceChangeResponseDataPriceChange.  # noqa: E501
        :rtype: float
        """
        return self._change_usd

    @change_usd.setter
    def change_usd(self, change_usd):
        """Sets the change_usd of this PublicPriceChangeResponseDataPriceChange.


        :param change_usd: The change_usd of this PublicPriceChangeResponseDataPriceChange.  # noqa: E501
        :type: float
        """
        if change_usd is None:
            raise ValueError("Invalid value for `change_usd`, must not be `None`")  # noqa: E501

        self._change_usd = change_usd

    @property
    def change_pct(self):
        """Gets the change_pct of this PublicPriceChangeResponseDataPriceChange.  # noqa: E501


        :return: The change_pct of this PublicPriceChangeResponseDataPriceChange.  # noqa: E501
        :rtype: float
        """
        return self._change_pct

    @change_pct.setter
    def change_pct(self, change_pct):
        """Sets the change_pct of this PublicPriceChangeResponseDataPriceChange.


        :param change_pct: The change_pct of this PublicPriceChangeResponseDataPriceChange.  # noqa: E501
        :type: float
        """
        if change_pct is None:
            raise ValueError("Invalid value for `change_pct`, must not be `None`")  # noqa: E501

        self._change_pct = change_pct

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PublicPriceChangeResponseDataPriceChange, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PublicPriceChangeResponseDataPriceChange):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
